# Generated by Django 2.2.10 on 2021-03-16 16:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0002_auto_20210315_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('background', models.ImageField(blank=True, null=True, upload_to='event_background_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
