# Generated by Django 2.2.10 on 2021-03-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0003_event_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tagline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
