# Generated by Django 2.2.10 on 2021-03-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0004_event_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='background_final',
            field=models.ImageField(blank=True, help_text='image for finish and results page', null=True, upload_to='event_background_img/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='background',
            field=models.ImageField(blank=True, help_text='image for landing page and question page', null=True, upload_to='event_background_img/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tagline',
            field=models.TextField(blank=True, help_text='Logo', null=True),
        ),
    ]
