# Generated by Django 2.2.10 on 2021-03-20 20:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0005_auto_20210320_2350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rules',
        ),
        migrations.RemoveField(
            model_name='event',
            name='background_final',
        ),
        migrations.AddField(
            model_name='event',
            name='rule',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
