# Generated by Django 2.2.10 on 2021-03-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0006_auto_20210321_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, upload_to='media/audios'),
        ),
    ]
