# Generated by Django 2.2.10 on 2021-03-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0008_auto_20210321_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sub_fin_color',
            field=models.CharField(default='', help_text='color code for question theme', max_length=100),
        ),
    ]
