# Generated by Django 2.2.10 on 2021-03-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0009_event_sub_fin_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sub_fin_color',
        ),
        migrations.AddField(
            model_name='event',
            name='button',
            field=models.CharField(default='', help_text='color code for submit and finish button', max_length=100),
        ),
    ]
