# Generated by Django 2.2.10 on 2021-03-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0010_auto_20210321_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='button',
            field=models.CharField(default='#008080', help_text='color code for submit and finish button', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='question_theme',
            field=models.CharField(default='#3b273b', help_text='color code for question theme', max_length=100),
        ),
    ]
