# Generated by Django 2.2.10 on 2021-03-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0011_auto_20210321_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='results_msg',
            field=models.TextField(blank=True, default='Results of Prelims are here!\nCongratulations to all!'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='logo of the event', null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='navbar_theme',
            field=models.CharField(default='#3b273b', help_text='color code for question theme', max_length=100),
        ),
    ]
